export const DISPLAY_ALERT = 'SHOW_ALERT'
export const MAX_ALERT = 'SHOW_MAX_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_STORY_BEGIN = 'CREATE_STORY_BEGIN'
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS'
export const CREATE_STORY_ERROR = 'CREATE_STORY_ERROR'

export const CREATE_LOG_SUCCESS = 'CREATE_LOG_SUCCESS'
export const GET_LOGS_SUCCESS = 'GET_LOGS_SUCCESS'

export const GET_STORIES_BEGIN = 'GET_STORIES_BEGIN'
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS'
export const GET_USERS_SUCCESS= 'GET_USERS_SUCCESS'
export const GET_REPLIES_SUCCESS= 'GET_REPLIES_SUCCESS'
export const GET_SUBREPLIES_SUCCESS = 'GET_SUBREPLIES_SUCCESS'

export const SET_EDIT_STORY = 'SET_EDIT_STORY'
export const SET_EDIT_LOG = 'SET_EDIT_LOG'

export const DELETE_STORY_BEGIN = 'DELETE_STORY_BEGIN'

export const EDIT_STORY_BEGIN = 'EDIT_STORY_BEGIN'
export const   EDIT_STORY_SUCCESS= 'EDIT_STORY_SUCCESS'
export const   EDIT_LOG_SUCCESS= 'EDIT_LOG_SUCCESS'


export const EDIT_STORY_ERROR = 'EDIT_STORY_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'
